PMM-7: fix lint errors
percona/pmm pull request #1128
Opened 2022-08-04 16:53 UTC by ritbl

PMM-7

2022-08-04 16:54 UTC, ritbl commented on admin/commands/inventory/list_agents.go
> -	res = strings.Title(strings.ToLower(res))
deprecated

2022-08-04 16:54 UTC, ritbl commented on agent/agents/mysql/perfschema/perfschema.go
> +				b.Common.ExampleFormat = agentpb.ExampleFormat_EXAMPLE // nolint:staticcheck
I think it is safer for now to ignore

2022-08-04 17:42 UTC, BupycHuk approved these changes

2022-08-05 06:31 UTC, michal-kralik approved these changes

2022-08-05 12:19 UTC, artemgavrilov requested changes

2022-08-05 12:19 UTC, artemgavrilov commented on agent/agents/postgres/pgstatmonitor/pgstatmonitor.go
> +		running = true // nolint: ineffassign
I think that linter warning actually highlights the problem. That variable overwritten on line 255.

2022-08-05 12:19 UTC, artemgavrilov commented on agent/utils/depstests/protobuf_test.go
> +	"github.com/golang/protobuf/jsonpb" //nolint:staticcheck
I think that one was also a good warning

2022-08-05 12:19 UTC, artemgavrilov commented on managed/services/management/azure_database.go
> +	"github.com/Azure/azure-sdk-for-go/services/resourcegraph/mgmt/2019-04-01/resourcegraph" // nolint:staticcheck
And that one

2022-08-05 12:19 UTC, artemgavrilov commented on agent/agents/postgres/pgstatmonitor/pgstatmonitor.go
> +				mb.Common.ExampleFormat = agentpb.ExampleFormat_EXAMPLE // nolint:staticcheck
Can you please create ticket for that. Otherwise we will forget about that problem.

2022-08-17 14:35 UTC, closed without merging