PMM-10457 More friendly documentation for fresh contributors
percona/pmm pull request #1170
Opened 2022-08-26 07:25 UTC by gen1us2k

PMM-0

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-08-26 09:29 UTC, gen1us2k commented
I moved DBaaS related documentation to the [dbaas-controller repo](https://github.com/percona-platform/dbaas-controller/pull/341)

2022-08-26 11:20 UTC, BupycHuk approved these changes
Great job

2022-08-29 10:10 UTC, palash25 approved these changes

2022-08-30 12:31 UTC, atymchuk commented on CONTRIBUTING.md
> +We're glad that you would like to become a Percona community member and participate in keeping open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-to
> We're glad that you would like to become a Percona community member
This seems to be too pretentious, we need to rephrase it.

2022-08-30 12:36 UTC, atymchuk requested changes

2022-08-30 12:36 UTC, atymchuk commented on CONTRIBUTING.md
> +We're glad that you would like to become a Percona community member and participate in keeping open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-to
```suggestion
We'd be glad to welcome to Percona community which tries to keep the open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-tools/percona-monitoring-and-management) is an open source database monitoring solution. It allows you to monitor your databases, different services (HAProxy, ProxySQL and etc) as well as Nodes, Kubernetes clusters and containers. Please check our [Documentation](https://docs.percona.com/percona-monitoring-and-management/details/architecture.html) for the actual architecture.
```

2022-08-30 12:36 UTC, atymchuk commented on CONTRIBUTING.md
> +We're glad that you would like to become a Percona community member and participate in keeping open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-to
See en example below.

2022-08-30 12:38 UTC, atymchuk commented on CONTRIBUTING.md
> +We're glad that you would like to become a Percona community member and participate in keeping open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-to
See an example below.

2022-09-05 08:43 UTC, atymchuk requested changes

2022-09-05 08:43 UTC, atymchuk commented on CONTRIBUTING.md
> +We'd be glad to welcome to Percona community which tries to keep the open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-tools/percona-monitoring-and
```suggestion
We'd be glad to welcome you to Percona community which tries to keep the open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-tools/percona-monitoring-and-management) is an open source database monitoring solution. It allows you to monitor your databases, different services (HAProxy, ProxySQL and etc) as well as Nodes, Kubernetes clusters and containers. Please check our [Documentation](https://docs.percona.com/percona-monitoring-and-management/details/architecture.html) for the actual architecture.
```

2022-09-05 08:44 UTC, atymchuk commented on CONTRIBUTING.md
> +We'd be glad to welcome to Percona community which tries to keep the open source open. [Percona Monitoring and Management (PMM)](https://www.percona.com/software/database-tools/percona-monitoring-and
Just a minor change :)

2022-09-05 14:36 UTC, atymchuk approved these changes

2022-09-05 14:36 UTC, merged