PMM-10065 Change settings for VictoriaMetrics server
percona/pmm pull request #1185
Opened 2022-09-01 16:33 UTC by anton-bystrov

Increase lookbehind window at big instances (500+ nodes).
[PMM-10065](https://jira.percona.com/browse/PMM-10065)

2022-09-01 16:34 UTC, atymchuk commented on managed/services/supervisord/supervisord.go
> +    --search.maxSamplesPerQuery=1500000000
pls adjust the indent here

2022-09-05 13:34 UTC, BupycHuk approved these changes

2022-09-05 13:34 UTC, BupycHuk requested changes
please fix tests

2022-09-05 16:55 UTC, BupycHuk approved these changes

2022-09-09 07:59 UTC, atymchuk approved these changes

2022-09-09 09:06 UTC, merged