PMM-10626: pmm server install command
percona/pmm pull request #1207
Opened 2022-09-12 07:40 UTC by michal-kralik

PMM-10626

Build: SUBMODULES-0

2022-09-21 14:47 UTC, atymchuk requested changes

2022-09-21 14:47 UTC, atymchuk commented on build/scripts/build-client-binary
> +    if [[ $keep_pmm_binary != "1" ]]; then
If `pmm_version` is global, then we could put the code here from https://github.com/percona/pmm/pull/1207/files#diff-f6033d471a2409e0d14b46e8bb0d7ad855b5093ff9c109246c388706e819ed76R53-R55

2022-09-30 07:46 UTC, rishat-ishbulatov approved these changes

2022-09-30 17:39 UTC, artemgavrilov approved these changes
LGTM

2022-10-03 11:35 UTC, michal-kralik commented on admin/commands/pmm/server/docker/install.go
> +var ErrDockerNoAccess = fmt.Errorf("DockerNoAccess")
Originally I wanted to have a more descriptive error message but then realized most of the time we have the error message in format `%w: %s`.
This turns the error message into something like:
`DockerNoAccess: you have no access to Docker. Try running as root.`
versus
`no access to Docker: you have no access to Docker. Try running as root.`

This is consistent with other parts of the code.
Maybe a better error would be 
`You have no access to Docker. Try running as root (ERR_DOCKER_NO_ACCESS)`

or something along these lines.
Looking for feedback here.

2022-10-11 14:30 UTC, atymchuk approved these changes

2022-10-11 14:30 UTC, atymchuk commented on admin/commands/pmm/server/docker/install.go
> +var ErrDockerNoAccess = fmt.Errorf("DockerNoAccess")
I quite like the version of `DockerNoAccess: you have no access to Docker. Try running as root.`

2022-10-12 07:22 UTC, merged