PMM-8792 Configurable MongoDB query length.
percona/pmm pull request #1268
Opened 2022-09-29 10:07 UTC by JiriCtvrtka

PMM-9056

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-09-29 13:17 UTC, michal-kralik approved these changes

2022-09-29 21:32 UTC, percona-csalguero requested changes

2022-09-29 21:38 UTC, BupycHuk commented on agent/agents/mongodb/internal/profiler/aggregator/aggregator.go
> +		fingerprint, _ := truncate.Query(v.Fingerprint, a.maxQueryLength)
Hi, we don't group by fingerprint value, we group by query id

2022-09-30 05:28 UTC, JiriCtvrtka commented on agent/agents/mongodb/internal/profiler/profiler.go
> +	maxQueryLength int32
Please take a look:
https://github.com/percona/pmm/pull/1216#discussion_r978350785

2022-10-03 13:33 UTC, percona-csalguero approved these changes

2022-10-21 09:12 UTC, merged