ci: change percona-platform to actions
percona/pmm pull request #1316
Opened 2022-10-18 21:51 UTC by mintbomb27

Changes the source of percona-platform sourced actions of the following actions:
    * `percona-platform/checkout`
    * `percona-platform/setup-go`
    * `percona-platform/cache`
    * `percona-platform/setup-node`
    * `percona-platform/action-slack-notify`
 to their upstream versions.

- [ ] Links to other linked pull requests (optional).

2022-10-18 21:52 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=1316) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=1316) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=1316) it.</sub>

2022-10-20 09:40 UTC, artemgavrilov commented
@atymchuk Please add these actions to allow-list in repo settings
`actions/checkout@v3.0.2`
`actions/setup-go@v2.1.3`
`actions/cache@v2.1.2`
`actions/setup-node@v3.3.0`
`rtCamp/action-slack-notify@v2.2.0`

2022-10-20 15:47 UTC, BupycHuk approved these changes

2022-10-20 17:39 UTC, mintbomb27 commented
@BupycHuk @artemgavrilov Would be great if you could add the `hacktoberfest-accepted` label. Thank you!

2022-10-20 18:06 UTC, atymchuk requested changes

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/agent.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/api.yml
> +        uses: actions/checkout@v3.0.2
```suggestion
        uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/api.yml
> +        uses: actions/setup-go@v2.1.3
```suggestion
        uses: actions/setup-go@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/api.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/clean.yml
> +        uses: actions/setup-go@v2.1.3
```suggestion
        uses: actions/setup-go@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/clean.yml
> +        uses: actions/checkout@v3.0.2
```suggestion
        uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/clean.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/clean.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +        uses: actions/checkout@v3.0.2
```suggestion
        uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +        uses: actions/setup-go@v2.1.3
```suggestion
        uses: actions/setup-go@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +      - uses: actions/checkout@v3.0.2
```suggestion
      - uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +      - uses: actions/setup-node@v3.3.0
```suggestion
      - uses: actions/setup-node@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +        uses: rtCamp/action-slack-notify@v2.2.0
```suggestion
        uses: rtCamp/action-slack-notify@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +      - uses: actions/checkout@v3.0.2
```suggestion
      - uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/common.yml
> +        uses: rtCamp/action-slack-notify@v2.2.0
```suggestion
        uses: rtCamp/action-slack-notify@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/doc.yml
> +        uses: actions/checkout@v3.0.2
```suggestion
        uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/managed.yml
> +        uses: actions/checkout@v3.0.2
```suggestion
        uses: actions/checkout@v3
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/managed.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:06 UTC, atymchuk commented on .github/workflows/managed.yml
> +        uses: actions/cache@v2.1.2
```suggestion
        uses: actions/cache@v2
```

2022-10-20 18:50 UTC, mintbomb27 commented
@atymchuk Had given specific versions as it was requested so in #1307 . Have replaced the same with the requested versions. Please check again.

2022-10-21 13:46 UTC, artemgavrilov approved these changes

2022-10-22 02:00 UTC, merged