Update ansible build conditions for docker
percona/pmm pull request #1387
Opened 2022-11-09 11:12 UTC by selamanse

This is a improvement proposal for the pmm-server docker image so it can be built on different container / virt environments under some different linux distros.

Our problem is/was that with the current ansible virtualized docker environments will not be recognized under some circumstances. we tested this with a current ubuntu and docker-ce, manjaro with docker-ce and also macOS Monterey with Rancher-Desktop installed.

There will be eventually a follow up PR with a slightly modified docker image for local builds. 

Build: [verification-build](https://github.com/Percona-Lab/pmm-submodules/pull/2749)

2022-11-09 21:29 UTC, atymchuk requested changes

2022-11-09 21:29 UTC, atymchuk commented on build/ansible/roles/pmm2-images/tasks/main.yml
> +      when: ansible_facts.virtualization_type | default('') not in ['docker', 'container', 'containerd', 'kvm']
```suggestion
      when: ansible_facts.virtualization_type | default('') in ['docker', 'container', 'containerd', 'kvm']
```

2022-11-09 21:29 UTC, atymchuk commented on build/ansible/roles/pmm2-images/tasks/main.yml
> +      when: ansible_facts.virtualization_type | default('') not in ['docker', 'container', 'containerd', 'kvm']
```suggestion
      when: ansible_facts.virtualization_type | default('') in ['docker', 'container', 'containerd', 'kvm']
```

2023-02-14 18:11 UTC, closed without merging

2023-02-15 08:07 UTC, selamanse commented
thank you for your review ! I appreciate it.