PMM-11364 Added dbaas-operator to ListKubernetesClusterResponse
percona/pmm pull request #1562
Opened 2023-01-12 12:42 UTC by gen1us2k

PMM-11364

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2023-02-22 14:22 UTC, percona-csalguero approved these changes

2023-02-27 19:01 UTC, recharte requested changes

2023-02-27 19:01 UTC, recharte commented on managed/services/management/dbaas/kubernetes_server.go
>  			// FIXME: Uncomment it when FE will be ready
```suggestion
```

2023-07-26 10:25 UTC, gen1us2k commented
Won't do

2023-07-26 10:25 UTC, closed without merging