PMM-11267: Send info about mysql plugins to telemetry
percona/pmm pull request #1588
Opened 2023-01-18 17:52 UTC by dliakhov

PMM-11267: Send info about mysql plugins to telemetry in the JSON format

- https://github.com/percona/mysqld_exporter/pull/113 - changes in the mysqld_exporter

2023-01-25 13:42 UTC, 0leksii approved these changes

2023-01-25 14:35 UTC, pkadej approved these changes

2023-01-25 14:53 UTC, ritbl commented on managed/services/telemetry/config.default.yml
> +        label: "type"
please use numbers, otherwise if will cause sorting issue

2023-01-25 14:54 UTC, ritbl requested changes
please see my comment

2023-01-25 15:14 UTC, tshcherban approved these changes

2023-01-30 09:40 UTC, dliakhov commented on managed/services/telemetry/config.default.yml
> +        label: "type"
Fixed.

2023-02-07 11:31 UTC, idoqo approved these changes

2023-02-13 15:48 UTC, merged