PMM-11550 Add DBaaS Templates
percona/pmm pull request #1719
Opened 2023-02-14 10:46 UTC by recharte

PMM-11550

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2023-02-21 17:37 UTC, percona-csalguero requested changes

2023-02-21 17:37 UTC, percona-csalguero commented on managed/services/dbaas/kubernetes/client/client.go
> +		options.LabelSelector = labelSelector
Which one should remain?

2023-02-21 17:38 UTC, percona-csalguero requested changes
LGTM with minor comments

2023-02-22 14:58 UTC, gen1us2k approved these changes

2023-02-22 15:04 UTC, percona-csalguero approved these changes

2023-03-03 18:15 UTC, percona-csalguero approved these changes

2023-03-08 10:47 UTC, merged