PMM-11385 Moved default configuration to dbaas-operator
percona/pmm pull request #1763
Opened 2023-02-22 11:48 UTC by gen1us2k

PMM-0

Build: SUBMODULES-0

- Links to related pull requests (optional).

2023-02-22 13:51 UTC, percona-csalguero approved these changes

2023-02-22 14:40 UTC, recharte requested changes

2023-02-22 14:40 UTC, recharte commented on managed/Makefile
> +PMM_RELEASE_VERSION ?= 2.36.0
```suggestion
PMM_RELEASE_VERSION ?= $(shell git describe --always --dirty | cut -b2-)
```

2023-02-27 18:20 UTC, recharte approved these changes

2023-02-28 07:02 UTC, merged