PMM-7 Upgrade aws-iam-authenticator
percona/pmm pull request #1839
Opened 2023-03-08 11:15 UTC by gen1us2k

PMM-0

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

2023-03-08 23:42 UTC, atymchuk requested changes
This also needs to be reflected in the changelog, ex:  https://github.com/percona/pmm/pull/1839/files#diff-4d817096dcecb32f4bdc2c6f8d4ffa97cbb4e2960615d5847fbafe2dc971c370L75-L76

2023-04-24 17:33 UTC, BupycHuk approved these changes

2023-05-10 13:52 UTC, BupycHuk approved these changes

2023-06-05 11:41 UTC, gen1us2k commented
@atymchuk I added changelog

2023-06-05 11:43 UTC, atymchuk approved these changes

2023-06-06 15:32 UTC, merged