PMM-11762 Update grafana to 9.2.13
percona/pmm pull request #1858
Opened 2023-03-10 12:08 UTC by matejkubinec

PMM-11762

Link to the Feature Build: SUBMODULES-3128

- https://github.com/percona-platform/grafana/pull/629

2023-03-10 16:31 UTC, atymchuk requested changes

2023-03-10 16:44 UTC, matejkubinec commented on build/packages/rpm/server/SPECS/grafana.spec
> +- PMM-10881 Grafana 9.2.13
Good catch, forgot to update it.

2023-03-13 16:07 UTC, atymchuk approved these changes

2023-03-16 10:20 UTC, michal-kralik approved these changes

2023-03-16 10:24 UTC, merged