PMM-9374 external victoria metrics
percona/pmm pull request #1916
Opened 2023-03-28 18:52 UTC by BupycHuk

PMM-9374

Link to the Feature Build: SUBMODULES-3331

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

2023-03-31 11:26 UTC, idoqo approved these changes

2023-04-04 12:43 UTC, rishat-ishbulatov commented on managed/services/supervisord/logs.go
>  	return &Logs{
Can we separate concrete implementation with abstract one? For example vmParams getter? Than if in future we change mechanism that gets us a new vmParams we wont rewrite this place?

2023-04-04 12:52 UTC, rishat-ishbulatov commented on managed/services/agents/state.go
> -		db:   db,
Can we separate concrete implementation with abstract one?

2023-04-04 12:59 UTC, rishat-ishbulatov requested changes
cool )

2023-04-04 13:17 UTC, BupycHuk commented on managed/models/victoriametrics_params.go
> +}
1. Passing a separate environment variable.
2. parsing URL and checking for a host value. if it's 127.0.0.1 or localhost

2023-04-04 18:56 UTC, rishat-ishbulatov commented on managed/models/victoriametrics_params.go
> +}
ok

2023-04-04 18:57 UTC, rishat-ishbulatov approved these changes

2023-09-18 10:01 UTC, merged