Lets to get security credentials if run on AWS FarGate
percona/pmm pull request #2174
Opened 2023-05-24 10:00 UTC by petlitskiy

PMM-0

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

2023-05-24 10:00 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=2174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=2174) before we can accept your contribution.<br/><hr/>**anonymous** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=2174) it.</sub>

2023-05-24 15:31 UTC, BupycHuk requested changes
Hi @petlitskiy,
thank you for your contribution.

Could you please sign the CLA, add to description what this PR is about and how it will help you?

I left a few comments what can be improved

Thank you

2023-05-25 07:01 UTC, petlitskiy commented on managed/services/agents/rds.go
> +        result := contains(envs, "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI.*")
The exactly env variable ("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI") ALWAYS is present only on AWS Fargate for PID 1

2023-05-25 07:10 UTC, petlitskiy commented on managed/services/agents/rds.go
> +        }
I used procfs, because needed env is present only for supervisord process. So it read from PID 1 envs, i.e. from supervisord envs.

2023-05-25 07:11 UTC, petlitskiy commented on managed/services/agents/rds.go
> +        }
This env is not present for managed process. It cannot be found with os.Environ()

2023-06-04 16:17 UTC, petlitskiy commented on managed/services/agents/rds.go
> +        result := contains(envs, "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI.*")
But yes - we can use os.GetEnv. I checked. It works well.

2023-06-06 06:45 UTC, BupycHuk approved these changes

2023-06-17 17:22 UTC, closed without merging

2023-06-28 18:38 UTC, petlitskiy commented
Yes. I'll reopen. But i confused with your CLA assistant plugin. I have no
idea what it wants from me.

ср, 28 черв. 2023, 15:58 користувач Artem Gavrilov ***@***.***>
пише:

> Hi @petlitskiy <https://github.com/petlitskiy> , sorry for the delay. Are
> you still interested in this contribution? We would like to merge this
> change, can you please reopen this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/percona/pmm/pull/2174#issuecomment-1611354041>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLN5D6O4PZ46ULYXRWIUMTXNQS73ANCNFSM6AAAAAAYNEB5QU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-29 08:59 UTC, artemgavrilov commented
@petlitskiy Please check that your email in git setting matches email specified in Github account, most likely this is the case.

2023-06-30 08:22 UTC, petlitskiy commented
Created again. https://github.com/percona/pmm/pull/2334

чт, 29 черв. 2023 р. о 11:59 Artem Gavrilov ***@***.***> пише:

> @petlitskiy <https://github.com/petlitskiy> Please check that your email
> in git setting matches email specified in Github account, most likely this
> is the case.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/percona/pmm/pull/2174#issuecomment-1612665706>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLN5D3PFOXUTFZU23KDIXTXNU7Y3ANCNFSM6AAAAAAYNEB5QU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-30 08:50 UTC, petlitskiy commented
This a pretty small but meaningful improvement can make our work much more
convenient. P.S. my colleague/chief like to update from PMM console. But to
update from PMM console it the rds agent has to work inside ECS Fargate.

пт, 30 черв. 2023 р. о 11:22 Олексій Петлицький ***@***.***>
пише:

> Created again. https://github.com/percona/pmm/pull/2334
>
> чт, 29 черв. 2023 р. о 11:59 Artem Gavrilov ***@***.***>
> пише:
>
>> @petlitskiy <https://github.com/petlitskiy> Please check that your email
>> in git setting matches email specified in Github account, most likely this
>> is the case.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/percona/pmm/pull/2174#issuecomment-1612665706>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATLN5D3PFOXUTFZU23KDIXTXNU7Y3ANCNFSM6AAAAAAYNEB5QU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>