Godot linter
percona/pmm pull request #2445
Opened 2023-08-30 10:37 UTC by vishwas-sharma2480

Description:
Ref: #1541

Summary:
When enabling the Godot rule, the period config parameter was intentionally set to false to avoid making the pull request too heavy for review. This change aims to turn it back to true (period: true) in the .golangci.yml file. This adjustment will cause the linter to fail when it encounters the absence of a period at the end of a comment, aligning with Go's conventions and best practices.

Suggested Solution:

Set the period parameter to true in the .golangci.yml configuration file.
Address and resolve any resulting linter warnings.
Additional Context:
I have already fixed the issue and am prepared to create this pull request. The proposed changes align with Go's coding conventions and should enhance the quality of the codebase.

2023-08-30 10:42 UTC, atymchuk commented on .github/workflows/codesee-arch-diagram.yml
> +# This workflow was added by CodeSee. Learn more at https://codesee.io/
I don't think we can use this action for a number of reasons, one of which being vendor validation, which is an entire process, that entails a request, a justification, a security check, and more.

Can we skip this for now?

2023-08-30 10:44 UTC, atymchuk commented
> Description: Ref: #1541

It refers rather to #2268

2023-08-30 10:48 UTC, artemgavrilov requested changes
Great job! 👏

Can you please address my comment about CI and resolve conflicts? Thank you!

2023-08-30 10:48 UTC, artemgavrilov commented on .github/workflows/codesee-arch-diagram.yml
> +# This workflow was added by CodeSee. Learn more at https://codesee.io/
Please remove this workflow. Any CI changes should be proposed in separate PR. But I'm not sure that we ready to add something like this now.

2023-08-30 10:48 UTC, artemgavrilov commented on agent/runner/actions/common.go
> +// ].
That one is weird, but ok 😁

2023-08-30 12:17 UTC, vishwas-sharma2480 commented
HI @artemgavrilov I have removed the file from my repo should i raise a new request

2023-08-30 12:50 UTC, artemgavrilov commented
> HI @artemgavrilov I have removed the file from my repo should i raise a new request

Great, now only conflicts resolving is left. Once its done just click `Re-request review` for me and Alex.

2023-08-30 14:23 UTC, artemgavrilov commented
@vishwas-sharma2480 Conflicts should be resolved before merging. In this case you need to merge(sync) upstream to your fork and resolve conflicts there.

2023-08-31 08:28 UTC, atymchuk commented
I was able to resolve the conflicts just by merging the `main` branch to this one. Could you please try the same?

2023-08-31 09:03 UTC, vishwas-sharma2480 commented
Hi Artem

But for that I might need access to merge to main
Best regards
Vishwas

On Thu, 31 Aug 2023, 13:59 Alex Tymchuk, ***@***.***> wrote:

> I was able to resolve the conflicts just by merging the main branch to
> this one. Could you please try the same?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/percona/pmm/pull/2445#issuecomment-1700593202>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAGMXGM7TYKRCFML4XJLLUDXYBDNLANCNFSM6AAAAAA4EJV2TA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-31 16:24 UTC, vishwas-sharma2480 commented
Hi @atymchuk 
I merged from my end and  i am not seeing any conflicts now

2023-08-31 17:05 UTC, artemgavrilov approved these changes

2023-08-31 21:08 UTC, artemgavrilov approved these changes
CI failure is unrelated to changes in this PR. 
We can merge it.

2023-09-01 09:42 UTC, atymchuk approved these changes

2023-09-01 09:43 UTC, merged