PMM-12677 stt naming cleanup
percona/pmm pull request #2805
Opened 2024-02-01 01:38 UTC by idoqo

PMM-12677

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

2024-02-01 12:12 UTC, BupycHuk approved these changes

2024-02-01 12:12 UTC, BupycHuk requested changes
Tests are failing, please check them

2024-02-02 07:58 UTC, ademidoff commented on api/management/v1/checks.proto
> +      post: "/v1/management/AdvisorChecks/ListFailedServices"
I'd prefer `/Advisor` as well )

2024-02-07 09:53 UTC, artemgavrilov approved these changes

2024-02-07 10:46 UTC, ademidoff approved these changes

2024-02-07 11:27 UTC, merged