PMM-12910 snooze updates
percona/pmm pull request #3018
Opened 2024-06-06 08:45 UTC by idoqo

PMM-12910

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

2024-06-10 07:58 UTC, ademidoff commented on managed/services/user/user.go
> +		if req.SnoozedPmmVersion != "" {
I feel we should either honor this linter request or disable the `protogetter` rule for all.

2024-07-23 00:52 UTC, BupycHuk requested changes

2024-07-23 00:52 UTC, BupycHuk commented on api/userpb/user.proto
> +  google.protobuf.StringValue snoozed_pmm_version = 4;
let's use
```suggestion
  optional string snoozed_pmm_version = 4;
```
like everywhere else

2024-07-23 00:52 UTC, BupycHuk commented on managed/models/user_flags_helpers.go
> +	SnoozedPMMVersion string
let's have it as a pointer

2024-07-29 08:25 UTC, ademidoff approved these changes

2024-07-29 08:34 UTC, JiriCtvrtka approved these changes

2024-07-31 10:37 UTC, BupycHuk approved these changes

2024-08-19 08:29 UTC, merged