PMM-13633 Doc for migration of API keys.
percona/pmm pull request #3420
Opened 2024-12-27 08:38 UTC by JiriCtvrtka

PMM-13633

Link to the Feature Build: SUBMODULES-0

2025-01-09 08:17 UTC, JiriCtvrtka commented
Changes on BE:
1. A warning is displayed if the authentication method is not a service account/token.
2. Adds the SnoozedAPIKeysMigration parameter for users to snooze the modal about deprecated API keys.
3. Sanitization of service account/token names during creation is now handled on the Grafana side.

Managed failing because of modified Grafana.

2025-01-09 10:37 UTC, BupycHuk commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +In the menu, go to **Administration -> Users and Access -> Service Accounts**. Verify that all API Keys have been migrated and that the API Keys menu is no longer visible.
as we discussed yesterday can you please add curl command here?

2025-01-09 10:41 UTC, BupycHuk requested changes

2025-01-09 10:41 UTC, BupycHuk commented on managed/services/grafana/client.go
> +			l.Warning("you should migrate your API Key into Service Account")
let's show this warning after checking if it's API key. otherwise user will see this error for incorrect service token too.

2025-01-09 11:09 UTC, JiriCtvrtka commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +In the menu, go to **Administration -> Users and Access -> Service Accounts**. Verify that all API Keys have been migrated and that the API Keys menu is no longer visible.
Sure, sorry I forgot to do that. Added.

2025-01-09 11:10 UTC, JiriCtvrtka commented on managed/services/grafana/client.go
> +			l.Warning("you should migrate your API Key into Service Account")
Good point, thanks. Now warning will be visible only if it is API key.

2025-01-09 11:15 UTC, ademidoff approved these changes
Minor wording improvements

2025-01-09 11:15 UTC, ademidoff commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +Please replace admin:admin with your valid credentials. As reponse you will get migration details. Example:
```suggestion
Please replace admin:admin with your valid credentials. You will get the migration details in the response. Example:
```

2025-01-09 11:15 UTC, ademidoff commented on managed/services/grafana/client.go
> +				l.Warning("you should migrate your API Key into Service Account")
```suggestion
				l.Warning("you should migrate your API Key to a Service Account")
```

2025-01-09 11:19 UTC, BupycHuk approved these changes

2025-01-09 11:19 UTC, BupycHuk commented on managed/services/grafana/client.go
> +	// ErrFailedToGetToken means it failed to get user's token. Most likely due to the fact user is not logged in using Percona Account.
Should it be Percona Account or Grafana account?

2025-01-09 11:20 UTC, JiriCtvrtka commented on managed/services/grafana/client.go
> +	ErrFailedToGetToken = errors.New("failed to get token")
This is actually not related to my changes, but it is between changes because I moved it inside var().  I am not sure if it is safe to change error message.

2025-01-09 11:23 UTC, JiriCtvrtka commented on managed/services/grafana/client.go
> +	// ErrFailedToGetToken means it failed to get user's token. Most likely due to the fact user is not logged in using Percona Account.
As I said to Alex https://github.com/percona/pmm/pull/3420/files#r1908599241
This is not related to my changes, but it is between changes because I moved this error inside var().

2025-01-09 13:52 UTC, ademidoff commented on managed/services/grafana/client.go
> +	ErrFailedToGetToken = errors.New("failed to get token")
It'd only break a QA automation test, if this message is covered at all. Otherwise, I'm always striving to offer a better English :)

2025-01-09 15:22 UTC, catalinaadam commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +In the menu, go to **Administration -> Users and Access -> Service Accounts**. Verify that all API Keys have been migrated and that the API Keys menu is no longer visible.
```suggestion
```

2025-01-09 15:22 UTC, catalinaadam commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +You can also perform this via a CLI command:
```suggestion
### From CLI
You can also trigger the conversion with the following command, replacing `admin:admin` with your credentials:
```

2025-01-09 15:22 UTC, catalinaadam commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +`curl -X POST http://localhost:3000/api/serviceaccounts/migrate -u admin:admin -H "Content-Type: application/json"`
```suggestion
	      ```sh
	        Copycurl -X POST http://localhost:3000/api/serviceaccounts/migrate \
	        -u admin:admin \
	        -H "Content-Type: application/json
	      ```
	

```

2025-01-10 08:15 UTC, JiriCtvrtka commented on documentation/docs/pmm-upgrade/migrating_from_pmm_2.md
> +You can also trigger the conversion with the following command, replacing `admin:admin` with your credentials:
Or user can has different address and port. Instead of 127.0.0.1 and 3000. Maybe we can mention also this.

2025-01-10 15:00 UTC, catalinaadam approved these changes

2025-01-13 10:32 UTC, idoqo approved these changes

2025-01-14 08:55 UTC, merged