PMM-6460 Add pg stat agent type.
percona/pmm pull request #572
Opened 2020-08-28 07:50 UTC by JiriCtvrtka

2020-09-02 10:46 UTC, AlekSi commented
There seems to be something wrong with the workflow – @JiriCtvrtka keeps updating api/api.descriptor file. Why? Why do you run this Makefile target?

2020-09-02 10:49 UTC, JiriCtvrtka commented
@AlekSi Without that I getting error for make gen. I wanted discard it then. So please what I am doing wrong?

2020-09-02 10:50 UTC, AlekSi commented
Why this file exist, what it does, and what error you get?

2020-09-02 10:53 UTC, JiriCtvrtka commented
It contains info from proto files. 

For example when I change number for AgentStatus I getting:
Message field "10" on message "inventory.QANPostgreSQLPgStatMonitorAgent" was deleted

2020-09-02 10:55 UTC, AlekSi commented
You answered the question "what is it?", bit not "what it does?" and "why we need it?"

2020-09-02 10:57 UTC, JiriCtvrtka commented
Propably for python files?

2020-09-02 11:22 UTC, AlekSi commented
So you update that file because it stands in your way without knowing what it does. Got it. But why you don't do the same with the Go compiler, for example? If some code does not compile, you can disable compilation instead of fixing the problem.

Please read [this](https://developers.google.com/protocol-buffers/docs/proto#updating), [this](https://github.com/uber/prototool#prototool-break-check), [this](https://github.com/uber/prototool#prototool-descriptor-set), and [this](https://github.com/uber/prototool/blob/dev/docs/breaking.md).

2020-09-02 13:08 UTC, BupycHuk requested changes
You are making to much things out of scope of your task.

2020-09-02 13:08 UTC, BupycHuk commented on api/inventorypb/agents.proto
> +  QAN_POSTGRESQL_PGSTATMONITOR_AGENT = 11;
It'll break backward compatibility, that's why make gen is failing.

2020-09-07 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/pmm?pullRequest=572) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/percona/pmm?pullRequest=572) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: AlekSi<br/>:x: JiriCtvrtka<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/pmm?pullRequest=572) it.</sub>

2020-09-10 07:34 UTC, closed without merging

2020-09-10 07:34 UTC, JiriCtvrtka commented
https://github.com/percona/pmm/pull/577