PMM-6567 pg_stat_monitor
percona/pmm pull request #577
Opened 2020-09-10 07:34 UTC by JiriCtvrtka

2020-09-16 08:31 UTC, BupycHuk requested changes

2020-09-16 08:31 UTC, BupycHuk commented on api/inventorypb/agents.proto
> +message AddQANPostgreSQLPgStatMonitorAgentRequest {
we need `disable_query_examples` in this request and we need to pass it to pmm-agent like in slowlog agent.

2020-09-16 08:31 UTC, BupycHuk commented on api/managementpb/postgresql.proto
> +  bool qan_postgresql_pgstatmonitor_agent = 19;
let's add `disable_query_examples`

2020-09-17 07:36 UTC, closed without merging

2020-09-17 07:38 UTC, AlekSi commented
@JiriCtvrtka Please re-create for `release/2.11` branch