SAAS-140 Support mongodb timestamp
percona/pmm pull request #599
Opened 2020-10-19 19:34 UTC by palash25

2020-10-19 19:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/pmm?pullRequest=599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/percona/pmm?pullRequest=599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/pmm?pullRequest=599) it.</sub>

2020-10-21 18:32 UTC, BupycHuk commented
@palash25 please use `release/2.12` as base branch

2020-10-22 08:01 UTC, palash25 commented
this is breaking two tests in pmm-agent for some reason 

```
== CONT  TestAgentClosesConnection
=== CONT  TestAgentRequest
--- PASS: TestServerExitsWithGRPCError (0.00s)
    TestAgentClosesConnection: channel_test.go:86: 
                Error Trace:    channel_test.go:86
                                                        channel_test.go:335
                Error:          []error{(*status.Error)(0xc000318098), (*status.Error)(0xc0003180a0)} does not contain &status.Error{e:(*status.Status)(0xc000128a80)}
                Test:           TestAgentClosesConnection
                Messages:       rpc error: code = Unavailable desc = transport is closing
                                failed to receive message
                                github.com/percona/pmm-agent/client/channel.(*Channel).runReceiver
                                        /home/palash25/dev/go/src/github.com/percona/pmm-agent/client/channel/channel.go:199
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1373
    TestServerExitsWithUnknownError: channel_test.go:86: 
                Error Trace:    channel_test.go:86
                                                        channel_test.go:280
                Error:          []error{(*status.Error)(0xc000318080)} does not contain &status.Error{e:(*status.Status)(0xc0000470e0)}
                Test:           TestServerExitsWithUnknownError
                Messages:       rpc error: code = Unknown desc = EOF
                                failed to receive message
                                github.com/percona/pmm-agent/client/channel.(*Channel).runReceiver
                                        /home/palash25/dev/go/src/github.com/percona/pmm-agent/client/channel/channel.go:199
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1373
--- PASS: TestUnexpectedResponseFromServer (0.00s)
--- PASS: TestAgentClosesStream (0.00s)
--- FAIL: TestServerExitsWithUnknownError (0.01s)
--- PASS: TestServerRequest (0.01s)
    TestAgentRequestWithTruncatedInvalidUTF8: channel_test.go:86: 
                Error Trace:    channel_test.go:86
                                                        channel_test.go:140
                Error:          []error{(*status.Error)(0xc000318048)} does not contain &status.Error{e:(*status.Status)(0xc0005a8480)}
                Test:           TestAgentRequestWithTruncatedInvalidUTF8
                Messages:       rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
                                failed to send message
                                github.com/percona/pmm-agent/client/channel.(*Channel).send
                                        /home/palash25/dev/go/src/github.com/percona/pmm-agent/client/channel/channel.go:183
                                github.com/percona/pmm-agent/client/channel.(*Channel).SendRequest
                                        /home/palash25/dev/go/src/github.com/percona/pmm-agent/client/channel/channel.go:156
                                github.com/percona/pmm-agent/client/channel.TestAgentRequestWithTruncatedInvalidUTF8
                                        /home/palash25/dev/go/src/github.com/percona/pmm-agent/client/channel/channel_test.go:138
                                testing.tRunner
                                        /usr/local/go/src/testing/testing.go:991
                                runtime.goexit
                                        /usr/local/go/src/runtime/asm_amd64.s:1373
--- FAIL: TestAgentRequestWithTruncatedInvalidUTF8 (0.01s)
--- PASS: TestAgentRequest (0.01s)
^CFAIL  github.com/percona/pmm-agent/client/channel     6.665s
FAIL
```

2020-10-26 10:49 UTC, BupycHuk approved these changes

2020-10-26 17:43 UTC, AlekSi requested changes
> MarshalActionQuerySQLResult and MarshalActionQueryDocsResult should convert primitive.Timestamp to tspb.Timestamp just like time.Time.

There should not be a separate field or type for MongoDB timestamps

2020-10-27 16:12 UTC, AlekSi commented
@BupycHuk @artemgavrilov PTAL

2020-10-27 17:04 UTC, artemgavrilov approved these changes

2020-10-27 17:54 UTC, AlekSi approved these changes

2020-10-27 17:54 UTC, merged