PMM-6050 Add external group
percona/pmm pull request #606
Opened 2020-10-29 08:59 UTC by askomorokhov

https://jira.percona.com/browse/PMM-6050

2020-10-29 17:32 UTC, BupycHuk requested changes

2020-10-29 17:32 UTC, BupycHuk commented on api/inventorypb/services.proto
> +    (validator.field) = {
We don't need this validation because it's a response

2020-10-30 13:08 UTC, percona-csalguero approved these changes

2020-11-01 17:01 UTC, BupycHuk approved these changes

2020-11-04 13:54 UTC, merged