PMM-6983 Add force for unregister k8s
percona/pmm pull request #633
Opened 2020-12-02 13:30 UTC by JiriCtvrtka

2020-12-03 21:17 UTC, BupycHuk approved these changes
looks good to me, api descriptor from my PR?

2020-12-04 07:17 UTC, JiriCtvrtka commented
@BupycHuk As far as I remember I created this branch from release/2.13, maybe this is reason?

2020-12-04 10:21 UTC, AlekSi requested changes
This field has to be documented

2020-12-07 14:33 UTC, AlekSi commented on api/managementpb/dbaas/kubernetes.proto
> +  // even if it contains clusters.
```suggestion
  // even if it contains database clusters.
```

2020-12-07 14:34 UTC, JiriCtvrtka commented on api/managementpb/dbaas/kubernetes.proto
> +  // even if it contains clusters.
Sounds better. I will changed it.

2020-12-08 12:14 UTC, JiriCtvrtka commented
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1273

2020-12-08 14:02 UTC, merged