PMM-7145 Push mode by default.
percona/pmm pull request #659
Opened 2021-01-20 08:25 UTC by JiriCtvrtka

2021-01-20 10:09 UTC, AlekSi requested changes

2021-01-20 10:09 UTC, AlekSi commented on api/managementpb/rds.proto
>    // Metrics could be pushed to the server with vmagent,
No, they could not be with that API

2021-01-20 10:09 UTC, AlekSi commented on api/managementpb/rds.proto
> +  // Push metrics mode is not allowed for exporters running on pmm-server.
There no way to choose a different Node in that API

2021-01-20 21:10 UTC, BupycHuk approved these changes

2021-01-21 11:14 UTC, askomorokhov approved these changes

2021-01-22 17:19 UTC, merged