PMM-7306 Add disable collectors fields.
percona/pmm pull request #660
Opened 2021-01-22 09:07 UTC by askomorokhov

https://jira.percona.com/browse/PMM-7306

2021-01-26 10:39 UTC, BupycHuk requested changes
Mistake

2021-01-26 11:11 UTC, BupycHuk approved these changes

2021-01-26 11:24 UTC, JiriCtvrtka approved these changes

2021-01-27 16:32 UTC, AlekSi reviewed
What about RDS?

2021-01-28 09:33 UTC, askomorokhov commented
> What about RDS?

@AlekSi, Yes, I have asked this question to Roma.  RDS and external exporters are out of scope here. Added to ticket description.

2021-01-29 15:09 UTC, AlekSi commented on api/inventorypb/agents.proto
> +  // List of collector names to exclude from exporter.
```suggestion
  // List of disabled collector names.
```

Nothing "to" there. There same for other "model" messages, but not for requests

2021-01-29 15:09 UTC, AlekSi commented on api/inventorypb/agents.proto
> +  // List of collector names to exclude from exporter.
```suggestion
  // List of collector names to disable in this exporter.
```

The same in other requests

2021-02-04 10:51 UTC, merged