PMM-7405 Add skip connection checks when add external exporter.
percona/pmm pull request #679
Opened 2021-02-12 10:24 UTC by askomorokhov

https://jira.percona.com/browse/PMM-7405

2021-02-12 11:09 UTC, JiriCtvrtka approved these changes

2021-02-15 10:26 UTC, AlekSi commented
@askomorokhov Please resolve merge conflicts

2021-02-16 11:27 UTC, percona-csalguero approved these changes

2021-02-17 09:18 UTC, BupycHuk requested changes

2021-02-17 09:18 UTC, BupycHuk commented on api/Makefile
> -		managementpb/json/managementpb.json \
revert please

2021-02-17 09:18 UTC, BupycHuk commented on api/managementpb/external.proto
> +  bool skip_connection_checks = 21;
```suggestion
  bool skip_connection_check = 21;
```

2021-02-17 11:06 UTC, BupycHuk approved these changes

2021-02-18 15:23 UTC, merged