PMM-7728 Added Authentication Mechanism
percona/pmm pull request #721
Opened 2021-04-08 14:13 UTC by percona-csalguero

Added authentication mechanism to add mongo instance request.
Without this field, ssl will fail because by default MongoDB uses SCRAM but certs use X509.

2021-04-08 14:50 UTC, askomorokhov submitted a review, later dismissed

2021-04-09 08:13 UTC, JiriCtvrtka submitted a review, later dismissed

2021-04-12 16:09 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=721) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=721) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: percona-csalguero<br/>:x: Carlos Salguero<br/><hr/>**Carlos Salguero** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=721) it.</sub>

2021-04-13 10:11 UTC, BupycHuk requested changes

2021-04-13 10:11 UTC, BupycHuk commented on api/inventorypb/agents.proto
> +  // See https://docs.mongodb.com/manual/reference/parameters/#mongodb-parameter-param.authenticationMechanisms
shouldn't it be `https://docs.mongodb.com/manual/reference/connection-string/#mongodb-urioption-urioption.authMechanism`?

2021-04-13 11:36 UTC, BupycHuk approved these changes

2021-04-13 13:05 UTC, JiriCtvrtka approved these changes

2021-04-15 15:57 UTC, percona-csalguero commented
Closing this in favor of https://github.com/percona/pmm/pull/724

2021-04-15 15:57 UTC, closed without merging