PMM-7883 Add PMM single line installer.
percona/pmm pull request #732
Opened 2021-04-26 09:29 UTC by askomorokhov

2021-04-26 12:12 UTC, rnovikovP commented on get-pmm.sh
> +# curl -fsSLhttps://github.com/percona/pmm/blob/PMM-2/get-pmm.sh -o get-pmm2.sh ; chmod +x get-pmm2.sh ; ./get-pmm2.sh
```suggestion
# curl -fsSLhttps://github.com/percona/pmm/blob/PMM-2.0/get-pmm.sh -o get-pmm2.sh ; chmod +x get-pmm2.sh ; ./get-pmm2.sh
```

? I assume the branch will be the same as we have now and it's PMM-2.0 for now

2021-04-26 13:29 UTC, percona-csalguero submitted a review, later dismissed

2021-04-26 15:16 UTC, percona-csalguero submitted a review, later dismissed

2021-04-26 23:18 UTC, BupycHuk submitted a review, later dismissed

2021-04-27 09:32 UTC, atymchuk requested changes

2021-04-27 09:32 UTC, atymchuk commented on get-pmm.sh
> +# If docker is not installed - this script try to install it as root user.
```suggestion
# If docker is not installed, this script will try to install it as root user.
```

2021-04-27 09:32 UTC, atymchuk commented on get-pmm.sh
> +  msg "So type '${PURPLE}thisisunsafe${NOFORMAT}' to bypass their warning"
This is Chrome only, Firefox won't have it. So need to mention it somehow.

2021-04-27 09:32 UTC, atymchuk commented on get-pmm.sh
> +  msg "So type '${PURPLE}thisisunsafe${NOFORMAT}' to bypass their warning"
```suggestion
  msg "So type '${PURPLE}thisisunsafe${NOFORMAT}' to bypass their warning (Chrome only)"
```

2021-04-27 09:32 UTC, atymchuk submitted a review, later dismissed

2021-04-27 15:43 UTC, percona-csalguero submitted a review, later dismissed

2021-04-30 13:43 UTC, percona-csalguero approved these changes

2021-04-30 18:05 UTC, atymchuk approved these changes

2021-05-04 09:49 UTC, percona-csalguero approved these changes

2021-05-04 10:51 UTC, merged