PMM-8514 refactoring
percona/pmm pull request #779
Opened 2021-09-26 12:03 UTC by BupycHuk

2021-09-30 14:06 UTC, jprukner approved these changes

2021-10-04 08:41 UTC, tiagomotasantos approved these changes

2021-10-04 08:48 UTC, tiagomotasantos reviewed
Created https://jira.percona.com/browse/PMM-8956 subtask two handle the change in the frontend.

The only change is that the list request now returns PXC and PSMDB clusters right?

2021-10-04 09:22 UTC, BupycHuk commented
@tiagomotasantos,I also renamed xtradb to pxc everywhere. except the places where we use it as `Percona XtraDB Cluster`.

2021-10-06 10:59 UTC, JiriCtvrtka approved these changes

2021-10-21 13:14 UTC, JiriCtvrtka submitted a review, later dismissed

2021-10-22 07:31 UTC, jprukner submitted a review, later dismissed

2021-11-08 11:44 UTC, tiagomotasantos requested changes

2021-11-08 11:44 UTC, tiagomotasantos commented on api/managementpb/dbaas/db_clusters.proto
> +      post: "/v1/management/DBaaS/PXCCluster/Restart"
```suggestion
      post: "/v1/management/DBaaS/DBClusters/Restart"
```

2021-11-08 13:04 UTC, BupycHuk commented on api/managementpb/dbaas/dbaas.proto
> +  // DB_CLUSTER_TYPE_PXC represents psmdb cluster type.
👍🏼

2021-11-10 12:45 UTC, palash25 approved these changes

2021-11-17 18:01 UTC, tiagomotasantos approved these changes

2021-12-01 15:13 UTC, merged