PMM-8588 Histogram.
percona/pmm pull request #793
Opened 2021-11-02 11:17 UTC by JiriCtvrtka

2021-11-02 15:13 UTC, BupycHuk approved these changes

2021-11-02 15:18 UTC, BupycHuk requested changes

2021-11-02 15:18 UTC, BupycHuk commented on api/agentpb/collector.proto
> +    repeated string histogram_items = 49;
I'm pretty sure that it could be repeated object or map.

2021-11-02 18:39 UTC, BupycHuk approved these changes

2021-11-03 15:52 UTC, percona-csalguero approved these changes

2021-11-03 15:53 UTC, merged