add path param to AgentInfo
percona/pmm pull request #818
Opened 2022-01-20 10:05 UTC by qwest812

2022-01-20 10:05 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=818) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=818) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=818) it.</sub>

2022-01-20 10:54 UTC, BupycHuk requested changes
Please, add a task number to PR header

2022-01-20 10:54 UTC, BupycHuk commented on api/agentlocalpb/agentlocal.proto
> +  string path = 5;
it probably should not be in AgentInfo, because it's not related to pmm-agent itself.
Just a path doesn't look a good naming
Please add comment.

2022-07-01 13:42 UTC, denisok commented
fixed in https://github.com/percona/pmm/pull/821 ?

2022-12-20 13:28 UTC, BupycHuk commented
Fixed in #821 and other PRs in other repositories

2022-12-20 13:28 UTC, closed without merging