Pmm 9378 refactor protobuf files
percona/pmm pull request #823
Opened 2022-02-04 09:23 UTC by PavelKhripkov

2022-02-04 09:23 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=823) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=823) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=823) it.</sub>

2022-02-07 11:01 UTC, BupycHuk approved these changes

2022-02-07 13:10 UTC, catalinaadam reviewed
Suggestions for improving readibility

2022-02-07 13:10 UTC, catalinaadam commented on api/serverpb/server.proto
> +      description: "Tests email alerting SMTP settings by sending testing email."
Sends test email to check current SMTP settings for email alerting.

2022-02-08 06:54 UTC, atymchuk requested changes
Good job! Just a minor correction please )

2022-02-08 06:54 UTC, atymchuk commented on api/serverpb/server.proto
> +      summary: "Readiness"
```suggestion
      summary: "Check server readiness"
```

2022-02-08 09:36 UTC, atymchuk submitted a review, later dismissed

2022-02-08 13:43 UTC, catalinaadam approved these changes

2022-02-08 15:52 UTC, catalinaadam approved these changes

2022-02-08 18:03 UTC, merged