Update golang, update bad dependencies
percona/pmm pull request #869
Opened 2022-04-15 14:10 UTC by artemgavrilov

PMM-7

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-04-16 08:53 UTC, BupycHuk requested changes
Good job, but CI is failing

2022-04-16 15:40 UTC, artemgavrilov commented
> Good job, but CI is failing

Dams, sorry. Fixed.

2022-04-17 10:53 UTC, BupycHuk approved these changes

2022-04-18 10:01 UTC, oksana-grishchenko approved these changes

2022-04-18 10:18 UTC, merged