PMM-9947: Encryption PoC
percona/pmm pull request #897
Opened 2022-05-17 10:35 UTC by ritbl

PMM-0

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

2022-06-16 10:56 UTC, BupycHuk requested changes
Thanks, finally I found a time to review this PR. Sorry for that.
How are we going to share public and private keys between pmm-admin and pmm-agent? Are we going to inject them during the build of PMM or just store them in repository or generate them on PMM managed side and share accross clients? 
If we will store them in repository than still it's not secure. pmm-admin allows to add agents to another host and if pmm-agent on another host doesn't support ecryption we will have a problem.
If we will inject keys during build we should disable encryption by default for builds made by community to not have problems with compatability.

Tests are failing. Please fix them.
Please fix linters as well.

2022-06-20 06:27 UTC, ritbl commented on admin/commands/management/add_mongodb.go
> +	encryptor := rsa_encryptor.GetEncryptor(ctx)
I'll fix the tests

2022-06-20 06:31 UTC, ritbl commented on utils/rsa_encryptor/encryptor.go
> +const (
Ok. Will make them private

2022-06-20 06:33 UTC, ritbl commented on utils/rsa_encryptor/encryptor.go
> +type Service struct {
>can we call it Encryptor?
ok

>Too many public methods, let's make methods private if we don't use them outside of this package.
What method/methods you think should be made private?

2022-06-20 06:51 UTC, ritbl commented
@BupycHuk 

>How are we going to share public and private keys between pmm-admin and pmm-agent?
We have multiple options:
1: Leave as it is in this PR - anyone with a bit of patience can find all the keys and decrypt data 
Security: 1 out of 5 (very bad). Just grab the keys from repo....
Ease of change / backward compatibility: 5 out of 5 (great).

2: Inject keys in the build time. Someone needs to generate keys and put in secrets in the repo.
Security: 2 out of 5 (bad). Keys will be embedded. It will make harder to get the key but it is still very easy.
Ease of change / backward compatibility: 4 out of 5 (good)

3: Inject keys before pmm starts. 
Security: 3-4 out of 5 (good). Proper solution will take time and client now need to manage the keys. It can be make semi-transparent, but still it will require a lot more work.
Ease of change / backward compatibility: 1 out of 5 (very bad)

We can start with any of these, the key can be rotated later. I think any solution would be better if we compare it with the current one.


>by default for builds made by community to not have problems with compatability
Actually, it is not needed. It will all work. It is backward compatible. We can start with key being even stored in source code (just because it is easy). Later we can provide better key management solution and create simple rotation job. The key name is embedded into metadata, so that we can have multiple keys.

2022-06-20 08:26 UTC, BupycHuk commented
> pmm-admin allows to add agents to another host; if pmm-agent on another host doesn't support encryption, we will have a problem.
it's not a typical case, but it's still possible.

2022-06-20 09:41 UTC, BupycHuk commented on utils/rsa_encryptor/encryptor.go
> +type Service struct {
I think I was clear here. All methods are not used outside of this package.

2022-06-20 09:44 UTC, ritbl commented
@BupycHuk 

>pmm-admin allows to add agents to another host; if pmm-agent on another host doesn't support encryption, we will have a problem.
>it's not a typical case, but it's still possible.

Admin perform encryption, for that public key is used. It doesn't need to be kept in secret.
We can embed public key and even put in the source code. Only private key should be taken care of (agent).

2022-09-16 08:53 UTC, atymchuk reviewed
@ritbl Do you mind if I convert it to draft to suppress notifications?

2023-06-07 12:16 UTC, closed without merging