restructure documentation and add common tech
percona/pmm pull request #973
Opened 2022-06-24 12:03 UTC by denisok

This PR restructures development documentation and moves Common Tech article from Confluence to GitHub

2022-06-24 12:17 UTC, atymchuk requested changes
This move entails a change on this line as well https://github.com/percona/pmm/pull/973/files#diff-7871fa1d10e6bf511d9cfda5a6874d1a75acb950fb1bc9fee6057eff13257521R35

2022-06-24 12:17 UTC, atymchuk commented on CONTRIBUTING.md
> +See [Working with Git and GitHub](dosc/process/GIT_AND_GITHUB.md)
```suggestion
See [Working with Git and GitHub](docs/process/GIT_AND_GITHUB.md)
```

2022-06-24 12:27 UTC, denisok commented
> This move entails a change on this line as well https://github.com/percona/pmm/pull/973/files#diff-7871fa1d10e6bf511d9cfda5a6874d1a75acb950fb1bc9fee6057eff13257521R35

done

2022-06-24 12:51 UTC, BupycHuk commented on docs/process/common_tech_lib_approaches.md
> +* [Kong](https://github.com/alecthomas/kong) for CLI.
let's mention that we use kingpin for exporters and some other components

2022-06-24 12:51 UTC, BupycHuk commented on docs/process/common_tech_lib_approaches.md
> +* `gofmt -s ` (note the `-s`)
we actually use `gofumpt`, also I think we should mention `make format` here

2022-06-24 12:55 UTC, BupycHuk commented
Can we add `docs/*` into paths-ignore in other workflows?

2022-06-24 13:03 UTC, denisok commented
> Can we add `docs/*` into paths-ignore in other workflows?

done

2022-06-24 13:08 UTC, BupycHuk commented on docs/process/common_tech_lib_approaches.md
> +* `gofmt -s ` (note the `-s`)
```suggestion
* `gofumt -s ` (note the `-s`)
* `make format`
```

2022-06-24 13:33 UTC, BupycHuk approved these changes

2022-06-24 13:47 UTC, BupycHuk submitted a review, later dismissed

2022-06-24 15:18 UTC, atymchuk approved these changes

2022-06-27 07:29 UTC, BupycHuk approved these changes

2022-06-27 07:30 UTC, merged